// constants.ts  (adds requirements so cards + detail can show them)
import { Hub } from './types';

export const HUB_TYPES: Hub['type'][] = ['Restaurant', 'Grocery', 'Church', 'Library'];

export const MOCK_HUBS: Hub[] = [
  {
    id: 'hub-1',
    name: 'Alvarado Community Diner',
    address: '101 N Parkway Dr, Alvarado, TX 76009',
    lat: 32.413,
    lng: -97.215,
    hours: '11am - 3pm Daily',
    offer: 'Free hot lunch (soup & sandwich)',
    dailyCap: 20,
    vouchersRemaining: 15,
    type: 'Restaurant',
    phone: '817-555-1234',
    selfAttestation: true,
    requirements: ['Photo ID (any)', 'Self-attest financial need'],
  },
  {
    id: 'hub-2',
    name: 'Johnson County Grocers',
    address: '850 S Parkway Dr, Alvarado, TX 76009',
    lat: 32.399,
    lng: -97.215,
    hours: '9am - 6pm Mon-Sat',
    offer: 'Bag of essential groceries (bread, milk, eggs)',
    dailyCap: 30,
    vouchersRemaining: 30,
    type: 'Grocery',
    phone: '817-555-5678',
    selfAttestation: true,
    requirements: ['EBT Card', 'Proof of residence in Johnson County', 'Past-due utility bill'],
  },
  {
    id: 'hub-3',
    name: 'First Baptist Church Alvarado',
    address: '207 E US-67, Alvarado, TX 76009',
    lat: 32.405,
    lng: -97.208,
    hours: '12pm - 2pm Tue, Thu',
    offer: 'Pantry items and canned goods',
    dailyCap: 50,
    vouchersRemaining: 42,
    type: 'Church',
    phone: '817-555-9012',
    selfAttestation: false,
    requirements: ['Photo ID (any)', 'One per household per week'],
  },
  {
    id: 'hub-4',
    name: 'The Burleson Bistro',
    address: '123 SW Wilshire Blvd, Burleson, TX 76028',
    lat: 32.536,
    lng: -97.325,
    hours: '8am - 2pm Daily',
    offer: 'Free coffee and a pastry',
    dailyCap: 40,
    vouchersRemaining: 8,
    type: 'Restaurant',
    phone: '817-555-3456',
    selfAttestation: true,
    requirements: ['Self-attest financial need'],
  },
  {
    id: 'hub-5',
    name: 'Alvarado Public Library',
    address: '210 N Baugh St, Alvarado, TX 76009',
    lat: 32.408,
    lng: -97.213,
    hours: '10am - 5pm M-F',
    offer: 'Emergency hygiene kits',
    dailyCap: 25,
    vouchersRemaining: 25,
    type: 'Library',
    phone: '817-555-7890',
    selfAttestation: false,
    requirements: ['Photo ID (any)', 'Library card (free sign-up available)'],
  },
];
